google_analytics_id: UA-56996624-2

repository: https://github.com/iROCKBUNNY/CV

timezone: Asia/Shanghai

title: About · Tong QU
description: Curriculum Vita
keywords: Tong QU, Curriculum Vitæ, CV, Resume
url: https://about.qutong.me

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net

contact: hello[at]qutong[dot]me
github: https://github.com/iROCKBUNNY

image: /images/avatar.jpg

plugins:
- jekyll-seo-tag

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- archive
- Gemfile
- Gemfile.lock
- script
- vendor